version: '3'
services:
  web:
    build: 
      &common-build
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      &common-volumes
      - /app/node_modules
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      *common-build
    volumes:
      *common-volumes
    command: ["npm", "run", "test"]